server:
  port: 4004
eureka:
  server:
    enable-self-preservation: false  #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #设置清理间隔（单位：毫秒 默认是60*1000）
  instance:
    hostname: eureka4004.com


  client:
#    registerWithEureka: false #不把自己作为一个客户端注册到自己身上默认是true
#    fetchRegistry: false  #不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用自己注册了）
    serviceUrl:
      defaultZone:  http://eureka4002.com:4002/eureka, http://eureka4003.com:4003/eureka